name: CIFuzz
on: workflow_dispatch:
permissions:
  contents: read
jobs:
  Fuzzing:
    runs-on: ubuntu-latest
    steps:
    - name: Build Fuzzers
      id: build
      uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@ec664edb5e484945cd3523fbc374eea24e999743 # master
      with:
        oss-fuzz-project-name: 'test'
        dry-run: false
    - name: Run Fuzzers
      uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@ec664edb5e484945cd3523fbc374eea24e999743 # master
      with:
        oss-fuzz-project-name: 'test'
        fuzz-seconds: 300
        dry-run: false
