name: Tesing clang step

on:
  workflow_dispatch:

permissions: 
  contents: read

jobs:
  clang-my:
    runs-on: windows-2019
    strategy:
      matrix:
        version: [11, 12, 13, 14, 15]

    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
      - name: Install Clang
        run: curl -fsSL -o LLVM${{ matrix.version }}.exe https://github.com/llvm/llvm-project/releases/download/llvmorg-${{ matrix.version }}.0.0/LLVM-${{ matrix.version }}.0.0-win64.exe ; 7z x LLVM${{ matrix.version }}.exe -y -o"C:/Program Files/LLVM"
      - name: Setup MSYS2 with tag comment
        uses: msys2/setup-msys2@7e5c1c8761fb96b55676bafd4fd3a641660c5d55 # v2.20.0
      - name: Setup MSYS2 with release comment
        uses: msys2/setup-msys2@ddf331adaebd714795f1042345e6ca57bd66cea8 # v2
