name: Tesing clang step

on:
  workflow_dispatch:

permissions: 
  contents: read

jobs:
  clang:
    runs-on: windows-2019
    strategy:
      matrix:
        version: [11, 12, 13, 14, 15]

    steps:
      - uses: actions/checkout@v3
      - name: Install Clang
        run: curl -fsSL -o LLVM${{ matrix.version }}.exe https://github.com/llvm/llvm-project/releases/download/llvmorg-${{ matrix.version }}.0.0/LLVM-${{ matrix.version }}.0.0-win64.exe ; 7z x LLVM${{ matrix.version }}.exe -y -o"C:/Program Files/LLVM"
