name: "Workflow with not pinned dependency"
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  simple-job:
    name: "Simple job"
    runs-on: ubuntu-latest
    steps:
#     - name: Checkout repository
#       uses: actions/checkout@v2 # GitHub-owned not pinned dependency
    - name: Setup R
    - uses: r-lib/actions/setup-r@f5b3dfbf1942ce68283de21bf65cce051e3a2c4d # v1
    - name: Install R packages
    - uses: r-lib/actions/setup-r-dependencies@v2 # Third-party not pinned dependency
