name: "Workflow with not pinned dependency"
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  simple-job:
    name: "Simple job"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2 # GitHub-owned not pinned dependency
    - name: Setup Go
      uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # Github-owned pinned dependency
      with:
        go-version: '>=1.17.0'
    - name: Setup Node
      uses: actions/setup-node@main # GitHub-owned not pinned dependency
      with:
        node-version: 16
    - name: Setup R
      uses: r-lib/actions/setup-r@d8b80f6aec8b653a0866f75b33e9c1401216bffe # Third-party pinned dependency
    - name: Install R packages
      uses: r-lib/actions/setup-r-dependencies@e6be4b3706e0f39bc7a4cf4496a5f2c4cb840040 # v2 # Third-party not pinned dependency
    - name: Install R packages
      uses: r-lib/actions/setup-r-dependencies@main # Third-party not pinned dependency
