name: "Test dangerous pattern"

on:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    # steps:
    # - name: Test script injection
    #   run: |
    #     echo "${{ github.event.pull_request.head.ref }}"
    #     if [[ ${{ github.event.pull_request.head.ref }} == owl-bot-copy ]]; then
    #       echo "Is owl-bot-copy"; else
    #       echo "Is NOT owl-bot-copy";
    #     fi
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            var title = context.payload.pull_request.title
            if (title == "octocat") {
              console.log("PR title is 'octocat'")
            }
            else {
              console.log("PR title is not 'octocat'")
            }
