name: Test vars on PRs
on:
  pull_request:

jobs:
  test-vars-on-pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
    - run: echo ${{ vars.VERSION }}
