name: "Test dangerous pattern"

on:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    # steps:
    # - name: Test script injection
    #   run: |
    #     echo "${{ github.event.pull_request.head.ref }}"
    #     if [[ ${{ github.event.pull_request.head.ref }} == owl-bot-copy ]]; then
    #       echo "Is owl-bot-copy"; else
    #       echo "Is NOT owl-bot-copy";
    #     fi
    if: github.head_ref == 'test-my-ref'
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            console.log(context.payload.pull_request.title);
            console.log(!context.payload.pull_request.title);
            console.log(!context.payload.pull_request.title === "chore: regenerate README");
            if (!context.payload.pull_request.title === "chore: regenerate README") {
              console.log("TRUE");
              return;
            }
            console.log("END")
