#   | Table       |
#   | ----------- |
#   | Lorem ipsum |
#   | Run actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 |
#   | Run actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3.5.1 |
#   | Run actions/checkout@v3 |
#   | Run actions/checkout@v3.5.1 |
#
#   Outside table scope
#   Run actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247
#   Run actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3.5.1
#   Run actions/checkout@v3
#   Run actions/checkout@v3.5.1

name: Test if comment with SHA is not updated by dependabot/renovatebot

on: workflow_dispatch

jobs:
  test-comment-with-sha:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3.5.1
