name: Test vars on PRs
on:
  pull_request:

jobs:
  test-vars-on-pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3.5.1
    - run: echo ${{ vars.VERSION }}
