#   | Table       |
#   | ----------- |
#   | Lorem ipsum |
#   | actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab |
#   | actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2 |
#   | actions/checkout@v3 |
#   | actions/checkout@v3.5.2 |
#
#   Outside table scope
#   actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
#   actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
#   actions/checkout@v3
#   actions/checkout@v3.5.2

name: Test if comment with SHA is not updated by dependabot/renovatebot

on: workflow_dispatch

jobs:
  test-comment-with-sha:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
