name: Test vars on PRs
on:
  pull_request:

jobs:
  test-vars-on-pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
    - run: echo ${{ vars.VERSION }}
