name: Unsafe var

on:
  pull_request:

env:
  PR_TITLE: ${{ github.event.pull_request.title }}

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [[ $PR_TITLE == owl-bot-copy ]]; then
            echo "PR is owl-bot-copy"
          fi
