name: Workflow with Vulnerability
on:
  workflow_dispatch:

permissions: {}

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1 # Avoids executing action with vulnerability
      - name: CSV export
        # Vulnerable action https://github.com/advisories/GHSA-634p-93h9-92vh
        uses: some-natalie/ghas-to-csv@3dc93f177ef97ce1623129977dc568589529a318  # v2
        env:
          GITHUB_PAT: "" # invalid PAT
